### 简介

```python
什么是异常：
	异常是程序发生错误的信号。程序一旦出现错误，便会产生一个异常，若程序中没有处理它，就会抛出该异常，程序的运行也随之终止。
    
	异常一般分为两种：
    	语法错误：
        	- 代码没有按照python规定语法去写,发明创造产生的错误
        逻辑错误：
			- 在代码语法正确的前提下,程序报错就是异常
```

### 异常处理

```
	为了保证程序的容错性与可靠性，即在遇到错误时有相应的处理机制不会任由程序崩溃掉，我们需要对异常进行处理，处理的基本形式为：
	try:
        被检测的代码块
    except 异常类型：
        检测到异常，就执行这个位置的逻辑

	本来程序一旦出现异常就整体结束掉了，有了异常处理以后，在被检测的代码块出现异常时，被检测的代码块中异常发生位置之后的代码将不会执行，取而代之的是执行匹配异常的except子代码块，其余代码均正常运行。
	
	当被检测的代码块中有可能触发不同类型的异常时，针对不同类型的异常：
	如果我们想分别用不同的逻辑处理，需要用到多分支的except（类似于多分支的elif，从上到下依次匹配，匹配成功一次便不再匹配其他）
        try:
            被检测的代码块
        except NameError:
            触发NameError时对应的处理逻辑
        except IndexError:
            触发IndexError时对应的处理逻辑
        except KeyError:
            触发KeyError时对应的处理逻辑

	如果我们想多种类型的异常统一用一种逻辑处理，可以将多个异常放到一个元组内，用一个except匹配
		try:
            被检测的代码块
        except (NameError,IndexError,TypeError):
            触发NameError或IndexError或TypeError时对应的处理逻辑


	如果我们想捕获所有异常并用一种逻辑处理，Python提供了一个万能异常类型Exception
		try:
            被检测的代码块
        except NameError:
            触发NameError时对应的处理逻辑
        except IndexError:
            触发IndexError时对应的处理逻辑
        except Exception:
            其他类型的异常统一用此处的逻辑处理

	在多分支except之后还可以跟一个else（else必须跟在except之后，不能单独存在），只有在被检测的代码块没有触发任何异常的情况下才会执行else的子代码块
		try:
            被检测的代码块
        except 异常类型1:
            pass
        except 异常类型2:
            pass
        ......
        else:
            没有异常发生时执行的代码块

	此外try还可以与finally连用，从语法上讲finally必须放到else之后，但可以使用try-except-finally的形式，也可以直接使用try-finally的形式。无论被检测的代码块是否触发异常，都会执行finally的子代码块，因此通常在finally的子代码块做一些回收资源的操作，比如关闭打开的文件、关闭数据库连接等
		try: 
			被检测的代码块 
		except 异常类型1: 
			pass 
		except 异常类型2: 
			pass 
			...... 
		else: 
			没有异常发生时执行的代码块 
		finally: 
			无论有无异常发生都会执行的代码块
	

```

### 主动抛出异常

```python

	在不符合Python解释器的语法或逻辑规则时，是由Python解释器主动触发的各种类型的异常，而对于违反程序员自定制的各类规则，则需要由程序员自己来明确地触发异常，这就用到了raise语句，raise后必须是一个异常的类或者是异常的实例
    	class Student:
            def __init__(self,name,age):
                if not isinstance(name,str):
                    raise TypeError('name must be str')
                if not isinstance(age,int):
                    raise TypeError('age must be int')

                self.name=name
                self.age=age

        stu1=Student(4573,18) # TypeError: name must be str
        stu2=Student('egon','18') # TypeError: age must be int

	在内置异常不够用的情况下，我们可以通过继承内置的异常类来自定义异常类
    	class PoolEmptyError(Exception): # 可以通过继承Exception来定义一个全新的异常
            def __init__(self,value='The proxy source is exhausted'): # 可以定制初始化方法
                super(PoolEmptyError,self).__init__()
                self.value=value

            def __str__(self): # 可以定义该方法用来定制触发异常时打印异常值的格式
                return '< %s >' %self.value


        class NetworkIOError(IOError): # 也可以在特定异常的基础上扩展一个相关的异常
            pass


        raise PoolEmptyError # __main__.PoolEmptyError: < The proxy source is exhausted >
        raise NetworkIOError('连接被拒绝') # __main__.NetworkIOError: 连接被拒绝

断言语句assert
	断言就是猜的意思
    assert 和 if 之间的区别在于
    assert 在断言失败时候,是直接报错,抛出异常,后面的代码直接终止了.
    if     在判断为False 的时候,不执行代码
		assert 3>1
        assert 3>1000
        print(res)
        print("ok")

```



### 异常的分类

```
IndexError                索引超出序列的范围
KeyError                  字典中查找一个不存在的关键字
NameError                 尝试访问一个不存在的变量
IndentationError          缩进错误
AttributeError            尝试访问未知的对象属性
StopIteration             迭代器没有更多的值
AssertionError			 断言语句（assert）失败
EOFError                  用户输入文件末尾标志EOF（Ctrl+d）
FloatingPointError        浮点计算错误
GeneratorExit             generator.close()方法被调用的时候
ImportError               导入模块失败的时候
KeyboardInterrupt         用户输入中断键（Ctrl+c）
MemoryError               内存溢出（可通过删除对象释放内存）
NotImplementedError       尚未实现的方法
OSError                   操作系统产生的异常（例如打开一个不存在的文件）
OverflowError             数值运算超出最大限制
ReferenceError            弱引用（weak reference）试图访问一个已经被垃圾回收机制回收了的对象
RuntimeError              一般的运行时错误
SyntaxError               Python的语法错误
TabError                  Tab和空格混合使用
SystemError               Python编译器系统错误
SystemExit                Python编译器进程被关闭
TypeError                 不同类型间的无效操作
UnboundLocalError         访问一个未初始化的本地变量（NameError的子类）
UnicodeError              Unicode相关的错误（ValueError的子类）
UnicodeEncodeError        Unicode编码时的错误（UnicodeError的子类）
UnicodeDecodeError        Unicode解码时的错误（UnicodeError的子类）
UnicodeTranslateError     Unicode转换时的错误（UnicodeError的子类）
ValueError                传入无效的参数
ZeroDivisionError         除数为零
```
### 获取错误行号和文件名(了解)
```
#(了解)系统底层获取行数和文件名的函数( 只有在程序异常时才能触发 ) 
def return_errorinfo(n):
	import sys
	f = sys.exc_info()[2].tb_frame.f_back
	if n==1:		
		return str(f.f_lineno)      #返回当前行数
	elif n == 2:	
		return f.f_code.co_filename #返回文件名	
```

### python内置异常类

```python
BaseException:所有异常的基类,包括退出异常和非退出异常；
SystemExit: 解释器请求退出 
KeyboardInterrupt: 用户中断执行(通常是输入^C) 
Exception: 常规错误的基类 
StopIteration: 迭代器没有更多的值 
GeneratorExit: 生成器(generator)发生异常来通知退出 
ArithmeticError: 所有数值计算错误的基类 
FloatingPointError: 浮点计算错误 
OverflowError: 数值运算超出最大限制 
ZeroDivisionError: 除(或取模)零 (所有数据类型) 
AssertionError: 断言语句失败 
AttributeError: 对象没有这个属性 
EOFError: 没有内建输入,到达EOF标记 
EnvironmentError: 操作系统错误的基类 
IOError: 输入/输出操作失败 
OSError: 操作系统错误 
WindowsError: 系统调用失败 
ImportError: 导入模块/对象失败 
LookupError: 无效数据查询的基类 
IndexError: 序列中没有此索引(index) 
KeyError: 映射中没有这个键 
MemoryError: 内存溢出错误(对于Python 解释器不是致命的) 
NameError: 未声明/初始化对象 (没有属性) 
UnboundLocalError: 访问未初始化的本地变量 
ReferenceError: 弱引用(Weak reference)试图访问已经垃圾回收了的对象 
RuntimeError: 一般的运行时错误 
NotImplementedError: 尚未实现的方法 
SyntaxError: Python语法错误 
IndentationError: 缩进错误 
TabError: Tab和空格混用 
SystemError: 一般的解释器系统错误 
TypeError: 对类型无效的操作 
ValueError: 传入无效的参数 
UnicodeError: Unicode相关的错误 
UnicodeDecodeError: Unicode解码时的错误 
UnicodeEncodeError: Unicode编码时错误 
UnicodeTranslateError: Unicode转换时错误 
Warning: 警告的基类 
DeprecationWarning: 关于被弃用的特征的警告 
FutureWarning: 关于构造将来语义会有改变的警告 
OverflowWarning: 旧的关于自动提升为长整型(long)的警告 
PendingDeprecationWarning: 关于特性将会被废弃的警告 
RuntimeWarning: 可疑的运行时行为(runtime behavior)的警告 
SyntaxWarning: 可疑的语法的警告 
UserWarning: 用户代码生成的警告
```

